name = "go-backend-react-frontend"
enable_filestore = false
enable_gcs_fuse = false
enable_postgres = false
enable_mysql = false
enable_api_gateway = false
enable_secrets = false
enable_slack = false
enable_automated_deploys = false
enable_application_url = false
hostname = ""

[metadata]
  owner = "yomi.ogbalaja@applied.co"
  description = "Arcade starship shooter with leaderboard"
